### ISSUE TITLE
ERR_PROXY_CONNECTION_FAILED

### ISSUE THREAD

**Issue by altwasntavailable** [PiggyAwesome/Discord-Account-Generator#19]
```Traceback (most recent call last):
File "C:\Users\xxxx\xxxxx\xxxxx\Discord-Account-Generator-main\account_generator.py", line 26, in <module>
    driver.get("https://discord.com/register")
  File "C:\Users\xxxx\AppData\Local\Programs\Python\Python312\Lib\site-packages\selenium\webdriver\remote\webdriver.py", line 357, in get
    self.execute(Command.GET, {"url": url})
  File "C:\Users\xxxx\AppData\Local\Programs\Python\Python312\Lib\site-packages\selenium\webdriver\remote\webdriver.py", line 348, in execute
    self.error_handler.check_response(response)
  File "C:\Users\xxxx\AppData\Local\Programs\Python\Python312\Lib\site-packages\selenium\webdriver\remote\errorhandler.py", line 229, in check_response
    raise exception_class(message, screen, stacktrace)
selenium.common.exceptions.WebDriverException: Message: unknown error: net::ERR_PROXY_CONNECTION_FAILED```

**Comment by PiggyAwesome** [comment]
Did you add your proxies to the main.py file?

**Comment by Rax0Savage** [comment]
> Did you add your proxies to the main.py file?

what format should i add??

**Comment by PiggyAwesome** [comment]
user:pass@ip:port
or
ip:port

**Comment by PiggyAwesome** [comment]
Has your issue been resolved yet?

**Comment by PiggyAwesome** [comment]
Assumed error is fixed as no response from author.
